// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson693b863aDecodeGithubComGoParkMailRu20251VelvetPullsInternalModel(in *jlexer.Lexer, out *RequestContact) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "username":
			out.Username = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson693b863aEncodeGithubComGoParkMailRu20251VelvetPullsInternalModel(out *jwriter.Writer, in RequestContact) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix[1:])
		out.String(string(in.Username))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestContact) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson693b863aEncodeGithubComGoParkMailRu20251VelvetPullsInternalModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestContact) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson693b863aEncodeGithubComGoParkMailRu20251VelvetPullsInternalModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestContact) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson693b863aDecodeGithubComGoParkMailRu20251VelvetPullsInternalModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestContact) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson693b863aDecodeGithubComGoParkMailRu20251VelvetPullsInternalModel(l, v)
}
func easyjson693b863aDecodeGithubComGoParkMailRu20251VelvetPullsInternalModel1(in *jlexer.Lexer, out *ContactList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(ContactList, 0, 1)
			} else {
				*out = ContactList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Contact
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson693b863aEncodeGithubComGoParkMailRu20251VelvetPullsInternalModel1(out *jwriter.Writer, in ContactList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v ContactList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson693b863aEncodeGithubComGoParkMailRu20251VelvetPullsInternalModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ContactList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson693b863aEncodeGithubComGoParkMailRu20251VelvetPullsInternalModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ContactList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson693b863aDecodeGithubComGoParkMailRu20251VelvetPullsInternalModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ContactList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson693b863aDecodeGithubComGoParkMailRu20251VelvetPullsInternalModel1(l, v)
}
func easyjson693b863aDecodeGithubComGoParkMailRu20251VelvetPullsInternalModel2(in *jlexer.Lexer, out *Contact) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "name":
			out.Name = string(in.String())
		case "username":
			out.Username = string(in.String())
		case "avatar_path":
			if in.IsNull() {
				in.Skip()
				out.AvatarURL = nil
			} else {
				if out.AvatarURL == nil {
					out.AvatarURL = new(string)
				}
				*out.AvatarURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson693b863aEncodeGithubComGoParkMailRu20251VelvetPullsInternalModel2(out *jwriter.Writer, in Contact) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	if in.Name != "" {
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	if in.AvatarURL != nil {
		const prefix string = ",\"avatar_path\":"
		out.RawString(prefix)
		out.String(string(*in.AvatarURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Contact) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson693b863aEncodeGithubComGoParkMailRu20251VelvetPullsInternalModel2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Contact) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson693b863aEncodeGithubComGoParkMailRu20251VelvetPullsInternalModel2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Contact) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson693b863aDecodeGithubComGoParkMailRu20251VelvetPullsInternalModel2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Contact) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson693b863aDecodeGithubComGoParkMailRu20251VelvetPullsInternalModel2(l, v)
}
