// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: services/auth_service/delivery/proto/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Username        string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password        string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,3,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	Phone           string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_services_auth_service_delivery_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_service_delivery_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_service_delivery_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

func (x *RegisterUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_services_auth_service_delivery_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_service_delivery_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_services_auth_service_delivery_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_services_auth_service_delivery_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_service_delivery_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_service_delivery_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_services_auth_service_delivery_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_service_delivery_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponse.ProtoReflect.Descriptor instead.
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return file_services_auth_service_delivery_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginUserResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type LogoutUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutUserRequest) Reset() {
	*x = LogoutUserRequest{}
	mi := &file_services_auth_service_delivery_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutUserRequest) ProtoMessage() {}

func (x *LogoutUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_service_delivery_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutUserRequest.ProtoReflect.Descriptor instead.
func (*LogoutUserRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_service_delivery_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LogoutUserRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CheckLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLoginRequest) Reset() {
	*x = CheckLoginRequest{}
	mi := &file_services_auth_service_delivery_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLoginRequest) ProtoMessage() {}

func (x *CheckLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_service_delivery_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLoginRequest.ProtoReflect.Descriptor instead.
func (*CheckLoginRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_service_delivery_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *CheckLoginRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CheckLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLoginResponse) Reset() {
	*x = CheckLoginResponse{}
	mi := &file_services_auth_service_delivery_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLoginResponse) ProtoMessage() {}

func (x *CheckLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_service_delivery_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLoginResponse.ProtoReflect.Descriptor instead.
func (*CheckLoginResponse) Descriptor() ([]byte, []int) {
	return file_services_auth_service_delivery_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *CheckLoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_services_auth_service_delivery_proto_auth_proto protoreflect.FileDescriptor

const file_services_auth_service_delivery_proto_auth_proto_rawDesc = "" +
	"\n" +
	"/services/auth_service/delivery/proto/auth.proto\x12\x04auth\x1a\x1bgoogle/protobuf/empty.proto\"\x8e\x01\n" +
	"\x13RegisterUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12)\n" +
	"\x10confirm_password\x18\x03 \x01(\tR\x0fconfirmPassword\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"5\n" +
	"\x14RegisterUserResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"J\n" +
	"\x10LoginUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"2\n" +
	"\x11LoginUserResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"2\n" +
	"\x11LogoutUserRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"2\n" +
	"\x11CheckLoginRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"-\n" +
	"\x12CheckLoginResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId2\xd1\x01\n" +
	"\vAuthService\x12E\n" +
	"\fRegisterUser\x12\x19.auth.RegisterUserRequest\x1a\x1a.auth.RegisterUserResponse\x12<\n" +
	"\tLoginUser\x12\x16.auth.LoginUserRequest\x1a\x17.auth.LoginUserResponse\x12=\n" +
	"\n" +
	"LogoutUser\x12\x17.auth.LogoutUserRequest\x1a\x16.google.protobuf.Empty2Q\n" +
	"\x0eSessionService\x12?\n" +
	"\n" +
	"CheckLogin\x12\x17.auth.CheckLoginRequest\x1a\x18.auth.CheckLoginResponseBPZNgithub.com/go-park-mail-ru/2025_1_VelvetPulls/services/auth_service/pkg/authpbb\x06proto3"

var (
	file_services_auth_service_delivery_proto_auth_proto_rawDescOnce sync.Once
	file_services_auth_service_delivery_proto_auth_proto_rawDescData []byte
)

func file_services_auth_service_delivery_proto_auth_proto_rawDescGZIP() []byte {
	file_services_auth_service_delivery_proto_auth_proto_rawDescOnce.Do(func() {
		file_services_auth_service_delivery_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_auth_service_delivery_proto_auth_proto_rawDesc), len(file_services_auth_service_delivery_proto_auth_proto_rawDesc)))
	})
	return file_services_auth_service_delivery_proto_auth_proto_rawDescData
}

var file_services_auth_service_delivery_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_services_auth_service_delivery_proto_auth_proto_goTypes = []any{
	(*RegisterUserRequest)(nil),  // 0: auth.RegisterUserRequest
	(*RegisterUserResponse)(nil), // 1: auth.RegisterUserResponse
	(*LoginUserRequest)(nil),     // 2: auth.LoginUserRequest
	(*LoginUserResponse)(nil),    // 3: auth.LoginUserResponse
	(*LogoutUserRequest)(nil),    // 4: auth.LogoutUserRequest
	(*CheckLoginRequest)(nil),    // 5: auth.CheckLoginRequest
	(*CheckLoginResponse)(nil),   // 6: auth.CheckLoginResponse
	(*emptypb.Empty)(nil),        // 7: google.protobuf.Empty
}
var file_services_auth_service_delivery_proto_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.RegisterUser:input_type -> auth.RegisterUserRequest
	2, // 1: auth.AuthService.LoginUser:input_type -> auth.LoginUserRequest
	4, // 2: auth.AuthService.LogoutUser:input_type -> auth.LogoutUserRequest
	5, // 3: auth.SessionService.CheckLogin:input_type -> auth.CheckLoginRequest
	1, // 4: auth.AuthService.RegisterUser:output_type -> auth.RegisterUserResponse
	3, // 5: auth.AuthService.LoginUser:output_type -> auth.LoginUserResponse
	7, // 6: auth.AuthService.LogoutUser:output_type -> google.protobuf.Empty
	6, // 7: auth.SessionService.CheckLogin:output_type -> auth.CheckLoginResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_auth_service_delivery_proto_auth_proto_init() }
func file_services_auth_service_delivery_proto_auth_proto_init() {
	if File_services_auth_service_delivery_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_auth_service_delivery_proto_auth_proto_rawDesc), len(file_services_auth_service_delivery_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_services_auth_service_delivery_proto_auth_proto_goTypes,
		DependencyIndexes: file_services_auth_service_delivery_proto_auth_proto_depIdxs,
		MessageInfos:      file_services_auth_service_delivery_proto_auth_proto_msgTypes,
	}.Build()
	File_services_auth_service_delivery_proto_auth_proto = out.File
	file_services_auth_service_delivery_proto_auth_proto_goTypes = nil
	file_services_auth_service_delivery_proto_auth_proto_depIdxs = nil
}
