global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'app-services'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'app:8080'
          - 'auth:9091'
          - 'search:9091'
          - 'websocket:8082'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']