// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: services/csat_service/delivery/proto/csat.proto

package csatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_services_csat_service_delivery_proto_csat_proto_rawDescGZIP(), []int{0}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_services_csat_service_delivery_proto_csat_proto_rawDescGZIP(), []int{1}
}

func (x *Answer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *Answer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Answer) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type FullStatistics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	QuestionStatistics []*QuestionStatistic   `protobuf:"bytes,1,rep,name=question_statistics,json=questionStatistics,proto3" json:"question_statistics,omitempty"`
	AverageRating      float64                `protobuf:"fixed64,2,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FullStatistics) Reset() {
	*x = FullStatistics{}
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullStatistics) ProtoMessage() {}

func (x *FullStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullStatistics.ProtoReflect.Descriptor instead.
func (*FullStatistics) Descriptor() ([]byte, []int) {
	return file_services_csat_service_delivery_proto_csat_proto_rawDescGZIP(), []int{2}
}

func (x *FullStatistics) GetQuestionStatistics() []*QuestionStatistic {
	if x != nil {
		return x.QuestionStatistics
	}
	return nil
}

func (x *FullStatistics) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

type QuestionStatistic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AverageRating float64                `protobuf:"fixed64,2,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	AnswerCount   int32                  `protobuf:"varint,3,opt,name=answer_count,json=answerCount,proto3" json:"answer_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionStatistic) Reset() {
	*x = QuestionStatistic{}
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionStatistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionStatistic) ProtoMessage() {}

func (x *QuestionStatistic) ProtoReflect() protoreflect.Message {
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionStatistic.ProtoReflect.Descriptor instead.
func (*QuestionStatistic) Descriptor() ([]byte, []int) {
	return file_services_csat_service_delivery_proto_csat_proto_rawDescGZIP(), []int{3}
}

func (x *QuestionStatistic) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *QuestionStatistic) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *QuestionStatistic) GetAnswerCount() int32 {
	if x != nil {
		return x.AnswerCount
	}
	return 0
}

type UserActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	TotalAnswers  int32                  `protobuf:"varint,2,opt,name=total_answers,json=totalAnswers,proto3" json:"total_answers,omitempty"`
	AverageRating float64                `protobuf:"fixed64,3,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserActivity) Reset() {
	*x = UserActivity{}
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActivity) ProtoMessage() {}

func (x *UserActivity) ProtoReflect() protoreflect.Message {
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActivity.ProtoReflect.Descriptor instead.
func (*UserActivity) Descriptor() ([]byte, []int) {
	return file_services_csat_service_delivery_proto_csat_proto_rawDescGZIP(), []int{4}
}

func (x *UserActivity) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserActivity) GetTotalAnswers() int32 {
	if x != nil {
		return x.TotalAnswers
	}
	return 0
}

func (x *UserActivity) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

type GetQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionsResponse) Reset() {
	*x = GetQuestionsResponse{}
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionsResponse) ProtoMessage() {}

func (x *GetQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionsResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_services_csat_service_delivery_proto_csat_proto_rawDescGZIP(), []int{5}
}

func (x *GetQuestionsResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type CreateAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnswerRequest) Reset() {
	*x = CreateAnswerRequest{}
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnswerRequest) ProtoMessage() {}

func (x *CreateAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnswerRequest.ProtoReflect.Descriptor instead.
func (*CreateAnswerRequest) Descriptor() ([]byte, []int) {
	return file_services_csat_service_delivery_proto_csat_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAnswerRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *CreateAnswerRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateAnswerRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type GetStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statistics    *FullStatistics        `protobuf:"bytes,1,opt,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsResponse) Reset() {
	*x = GetStatisticsResponse{}
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsResponse) ProtoMessage() {}

func (x *GetStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_services_csat_service_delivery_proto_csat_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatisticsResponse) GetStatistics() *FullStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

type GetUserActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserActivityRequest) Reset() {
	*x = GetUserActivityRequest{}
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserActivityRequest) ProtoMessage() {}

func (x *GetUserActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserActivityRequest.ProtoReflect.Descriptor instead.
func (*GetUserActivityRequest) Descriptor() ([]byte, []int) {
	return file_services_csat_service_delivery_proto_csat_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserActivityRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUserActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *UserActivity          `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserActivityResponse) Reset() {
	*x = GetUserActivityResponse{}
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserActivityResponse) ProtoMessage() {}

func (x *GetUserActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_csat_service_delivery_proto_csat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserActivityResponse.ProtoReflect.Descriptor instead.
func (*GetUserActivityResponse) Descriptor() ([]byte, []int) {
	return file_services_csat_service_delivery_proto_csat_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserActivityResponse) GetActivity() *UserActivity {
	if x != nil {
		return x.Activity
	}
	return nil
}

var File_services_csat_service_delivery_proto_csat_proto protoreflect.FileDescriptor

const file_services_csat_service_delivery_proto_csat_proto_rawDesc = "" +
	"\n" +
	"/services/csat_service/delivery/proto/csat.proto\x12\x04csat\x1a\x1bgoogle/protobuf/empty.proto\".\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"]\n" +
	"\x06Answer\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\"\x81\x01\n" +
	"\x0eFullStatistics\x12H\n" +
	"\x13question_statistics\x18\x01 \x03(\v2\x17.csat.QuestionStatisticR\x12questionStatistics\x12%\n" +
	"\x0eaverage_rating\x18\x02 \x01(\x01R\raverageRating\"~\n" +
	"\x11QuestionStatistic\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12%\n" +
	"\x0eaverage_rating\x18\x02 \x01(\x01R\raverageRating\x12!\n" +
	"\fanswer_count\x18\x03 \x01(\x05R\vanswerCount\"v\n" +
	"\fUserActivity\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12#\n" +
	"\rtotal_answers\x18\x02 \x01(\x05R\ftotalAnswers\x12%\n" +
	"\x0eaverage_rating\x18\x03 \x01(\x01R\raverageRating\"D\n" +
	"\x14GetQuestionsResponse\x12,\n" +
	"\tquestions\x18\x01 \x03(\v2\x0e.csat.QuestionR\tquestions\"j\n" +
	"\x13CreateAnswerRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\"M\n" +
	"\x15GetStatisticsResponse\x124\n" +
	"\n" +
	"statistics\x18\x01 \x01(\v2\x14.csat.FullStatisticsR\n" +
	"statistics\"4\n" +
	"\x16GetUserActivityRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"I\n" +
	"\x17GetUserActivityResponse\x12.\n" +
	"\bactivity\x18\x01 \x01(\v2\x12.csat.UserActivityR\bactivity2\xaa\x02\n" +
	"\vCsatService\x12B\n" +
	"\fGetQuestions\x12\x16.google.protobuf.Empty\x1a\x1a.csat.GetQuestionsResponse\x12A\n" +
	"\fCreateAnswer\x12\x19.csat.CreateAnswerRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\rGetStatistics\x12\x16.google.protobuf.Empty\x1a\x1b.csat.GetStatisticsResponse\x12N\n" +
	"\x0fGetUserActivity\x12\x1c.csat.GetUserActivityRequest\x1a\x1d.csat.GetUserActivityResponseBPZNgithub.com/go-park-mail-ru/2025_1_VelvetPulls/services/csat_service/pkg/csatpbb\x06proto3"

var (
	file_services_csat_service_delivery_proto_csat_proto_rawDescOnce sync.Once
	file_services_csat_service_delivery_proto_csat_proto_rawDescData []byte
)

func file_services_csat_service_delivery_proto_csat_proto_rawDescGZIP() []byte {
	file_services_csat_service_delivery_proto_csat_proto_rawDescOnce.Do(func() {
		file_services_csat_service_delivery_proto_csat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_csat_service_delivery_proto_csat_proto_rawDesc), len(file_services_csat_service_delivery_proto_csat_proto_rawDesc)))
	})
	return file_services_csat_service_delivery_proto_csat_proto_rawDescData
}

var file_services_csat_service_delivery_proto_csat_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_services_csat_service_delivery_proto_csat_proto_goTypes = []any{
	(*Question)(nil),                // 0: csat.Question
	(*Answer)(nil),                  // 1: csat.Answer
	(*FullStatistics)(nil),          // 2: csat.FullStatistics
	(*QuestionStatistic)(nil),       // 3: csat.QuestionStatistic
	(*UserActivity)(nil),            // 4: csat.UserActivity
	(*GetQuestionsResponse)(nil),    // 5: csat.GetQuestionsResponse
	(*CreateAnswerRequest)(nil),     // 6: csat.CreateAnswerRequest
	(*GetStatisticsResponse)(nil),   // 7: csat.GetStatisticsResponse
	(*GetUserActivityRequest)(nil),  // 8: csat.GetUserActivityRequest
	(*GetUserActivityResponse)(nil), // 9: csat.GetUserActivityResponse
	(*emptypb.Empty)(nil),           // 10: google.protobuf.Empty
}
var file_services_csat_service_delivery_proto_csat_proto_depIdxs = []int32{
	3,  // 0: csat.FullStatistics.question_statistics:type_name -> csat.QuestionStatistic
	0,  // 1: csat.GetQuestionsResponse.questions:type_name -> csat.Question
	2,  // 2: csat.GetStatisticsResponse.statistics:type_name -> csat.FullStatistics
	4,  // 3: csat.GetUserActivityResponse.activity:type_name -> csat.UserActivity
	10, // 4: csat.CsatService.GetQuestions:input_type -> google.protobuf.Empty
	6,  // 5: csat.CsatService.CreateAnswer:input_type -> csat.CreateAnswerRequest
	10, // 6: csat.CsatService.GetStatistics:input_type -> google.protobuf.Empty
	8,  // 7: csat.CsatService.GetUserActivity:input_type -> csat.GetUserActivityRequest
	5,  // 8: csat.CsatService.GetQuestions:output_type -> csat.GetQuestionsResponse
	10, // 9: csat.CsatService.CreateAnswer:output_type -> google.protobuf.Empty
	7,  // 10: csat.CsatService.GetStatistics:output_type -> csat.GetStatisticsResponse
	9,  // 11: csat.CsatService.GetUserActivity:output_type -> csat.GetUserActivityResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_services_csat_service_delivery_proto_csat_proto_init() }
func file_services_csat_service_delivery_proto_csat_proto_init() {
	if File_services_csat_service_delivery_proto_csat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_csat_service_delivery_proto_csat_proto_rawDesc), len(file_services_csat_service_delivery_proto_csat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_csat_service_delivery_proto_csat_proto_goTypes,
		DependencyIndexes: file_services_csat_service_delivery_proto_csat_proto_depIdxs,
		MessageInfos:      file_services_csat_service_delivery_proto_csat_proto_msgTypes,
	}.Build()
	File_services_csat_service_delivery_proto_csat_proto = out.File
	file_services_csat_service_delivery_proto_csat_proto_goTypes = nil
	file_services_csat_service_delivery_proto_csat_proto_depIdxs = nil
}
