definitions:
  model.LoginCredentials:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  model.RegisterCredentials:
    properties:
      confirm_password:
        type: string
      password:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  title: Keftegram backend API
  version: "1.0"
paths:
  /api/login/:
    post:
      consumes:
      - application/json
      description: Авторизовывает, аутентифицирует существующего пользователя и возвращает
        token
      parameters:
      - description: Данные для авторизации пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.LoginCredentials'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Авторизация пользователя
      tags:
      - User Session
  /api/register/:
    post:
      consumes:
      - application/json
      description: Регистрирует нового пользователя по данным, переданным в запросе
        и возвращает token
      parameters:
      - description: Данные для регистрации пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.RegisterCredentials'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Регистрация нового пользователя
      tags:
      - User
swagger: "2.0"
